# Generated by Django 2.0.6 on 2019-08-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='company_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
