# Generated by Django 2.0.6 on 2019-10-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=200)),
                ('livephoto', models.CharField(max_length=200)),
                ('secdocument', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=200)),
                ('livephoto', models.CharField(max_length=200)),
                ('secdocument', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=200)),
                ('secondary_name', models.CharField(max_length=200)),
                ('secondary_id_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('mobile', models.BigIntegerField(null=True)),
                ('city', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=400)),
                ('isActive', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200, null=True)),
                ('token', models.CharField(default='', max_length=200, null=True)),
                ('time', models.CharField(default='', max_length=200, null=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('vehicle_image1', models.CharField(max_length=200, null=True)),
                ('codriver', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserRole'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserInfo'),
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserInfo'),
        ),
    ]
