# Generated by Django 2.0.6 on 2019-10-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=200)),
                ('livephoto', models.CharField(max_length=200)),
                ('secdocument', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=200)),
                ('secondary_name', models.CharField(max_length=200)),
                ('secondary_id_no', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserInfo')),
            ],
        ),
    ]
